-- TEST
DROP USER test CASCADE;

CREATE USER test IDENTIFIED BY test ;

GRANT RESOURCE,CONNECT TO test ;

ALTER USER test QUOTA UNLIMITED ON USERS;


-- SUGARCRM
DROP USER sugarcrm CASCADE;

CREATE USER sugarcrm IDENTIFIED BY sugarcrm ;

GRANT RESOURCE,CONNECT TO sugarcrm ;

ALTER USER sugarcrm QUOTA UNLIMITED ON USERS;


-- DWHADMIN
DROP USER dwhadmin CASCADE;

CREATE USER dwhadmin IDENTIFIED BY dwhadmin ;

GRANT RESOURCE,CONNECT, CREATE VIEW TO dwhadmin ;

ALTER USER dwhadmin QUOTA UNLIMITED ON USERS;


-- DWHADMIN_TEST
DROP USER dwhadmin_test CASCADE;

CREATE USER dwhadmin_test IDENTIFIED BY dwhadmin ;

GRANT RESOURCE,CONNECT, CREATE VIEW TO dwhadmin_test ;

ALTER USER dwhadmin_test QUOTA UNLIMITED ON USERS;




-- DWHSTAGE
DROP USER dwhstage CASCADE;

CREATE USER dwhstage IDENTIFIED BY dwhstage ;

GRANT RESOURCE,CONNECT, CREATE SYNONYM, CREATE DATABASE LINK TO dwhstage ;

ALTER USER dwhstage QUOTA UNLIMITED ON USERS;



-- DWHREPORT
DROP USER dwhreport CASCADE;

CREATE USER dwhreport IDENTIFIED BY dwhreport ;

GRANT RESOURCE,CONNECT, CREATE VIEW, CREATE SYNONYM TO dwhreport ;

ALTER USER dwhreport QUOTA UNLIMITED ON USERS;