-- TEST
DROP USER TEST CASCADE;

CREATE USER TEST IDENTIFIED BY "test";

GRANT CREATE SESSION TO TEST;
GRANT CREATE TABLE TO TEST;

CREATE SCHEMA TEST;

ALTER SCHEMA TEST CHANGE OWNER TEST;


-- SUGARCRM
DROP USER SUGARCRM CASCADE;

CREATE USER SUGARCRM IDENTIFIED BY "sugarcrm";

GRANT CREATE SESSION TO SUGARCRM;
GRANT CREATE TABLE TO SUGARCRM;

CREATE SCHEMA SUGARCRM;

ALTER SCHEMA SUGARCRM CHANGE OWNER SUGARCRM;


-- DWHSTAGE
DROP USER DWHSTAGE CASCADE;

CREATE USER DWHSTAGE IDENTIFIED BY "dwhstage";

GRANT CREATE SESSION TO DWHSTAGE;
GRANT CREATE TABLE TO DWHSTAGE;

CREATE SCHEMA DWHSTAGE;

ALTER SCHEMA DWHSTAGE CHANGE OWNER DWHSTAGE;