/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nicola' at '20/05/16 19:44' with Gradle 2.13
 *
 * @author Nicola, @date 20/05/16 19:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
